name: Build & Publish Gradle project

on:
  push:
    branches:
      - main
      - dev/dev

jobs:
  build-gradle-project:
    env:
      REPO_USER: ${{ secrets.REPO_USERNAME }}
      REPO_PASS: ${{ secrets.REPO_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          architecture: x64
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run shadowJar and publish with Gradle Wrapper
        run: ./gradlew plugin:shadowJarReobf plugin:shadowJarMojMap core:publish api:publish -ProxymcUsername=${{ env.REPO_USER }} -ProxymcPassword=${{ env.REPO_PASS }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: plugin/build/libs